version: '3.8'
x-common:
  database:
    &db-environment
    MYSQL_PASSWORD: &db-password "pwd"
    MYSQL_ROOT_PASSWORD: "pwd"
  panel:
    &panel-environment
    APP_URL: "https://panel.master.cloud.piarre.app"
    APP_TIMEZONE: "Europe/Paris"
    APP_SERVICE_AUTHOR: "contact@pierre-ide.fr"
    TRUSTED_PROXIES: "*"
  mail: &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

services:
  database:
    image: mariadb:10.5
    restart: always
    networks:
      - proxy
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
  cache:
    image: redis:alpine
    restart: always
    networks:
      - proxy
  panel:
    container_name: panel
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    networks:
      - proxy
    ports:
      - "81:80"
      - "444:443"
    links:
      - database
      - cache
    volumes:
      - "/srv/pterodactyl/var/:/app/var/"
      - "/srv/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "/srv/pterodactyl/certs/:/etc/letsencrypt/"
      - "/srv/pterodactyl/logs/:/app/storage/logs"
    environment:
      <<: [ *panel-environment, *mail-environment ]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`panel.master.cloud.piarre.app`)"
      - "traefik.http.routers.panel.entrypoints=websecure"
      - "traefik.http.routers.panel.tls.certresolver=myresolver"

networks:
  proxy:
    external: true